version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gocognit
    - gocyclo
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive

linters-settings:
  gocyclo:
    min-complexity: 15
  gocognit:
    min-complexity: 20
  errcheck:
    check-type-assertions: true
    check-blank: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
